##run环境 远程主机
##run方式 jar运行
#variables:
#  PROJECT_NAME: remote-desktop #项目名
#  RESOURCE: dist #转移的资源，当前路径为项目根目录
#  #=====远程服务器信息
#  RUN_SERVER_DOMAIN: root@39.98.203.31 #运行服务器-地址
#  SERVER_DOMAIN_PORT: 22 #运行服务器ssh端口
#  REMOTE_RESOURCE: /root/data/nginx #运行服务器-要运行的程序存放的位置
#
#include:
#  - project: deployment/gitlab-deployment
#    ref: master
#    file:
#      - /gitlab-runner/docker/static/ci-common/.gitlab-ci-common.yml
#      - /gitlab-runner/docker/static/ci-vue/.gitlab-ci-vue-run.yml
#
#before_script:
#  - source ~/.bashrc
##  - export NODE_HOME= #编译服务器-所需的node js环境
#
#ci_check:
#  only:
#    refs:
#      - master
#      - main
#      - /^issue-.*$/
#    changes:
#      - "**/*.json"
#      - "src"
#      - "**/*.js"
#  stage: ci_check
#  script: echo "Check, Rules!"
##  rules:
##    - if: ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main") && $CI_COMMIT_TITLE =~ /ci*/
##      when: on_success
#
#vue_compile:
#  stage: vue_compile
#  script:
#    - npm install
#    - npm run build
#    - echo "target:"`ls`
#
#stages:
#  - ci_check
#  - vue_compile
#  - remote_resource
